# Generated by Django 4.2.5 on 2024-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacheloreducationdetails',
            name='bachelor_others',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience_details',
            name='application_no',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
