# Generated by Django 5.0.4 on 2024-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='Department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
