# Generated by Django 5.0.4 on 2024-09-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_approver_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approver',
            name='Department',
        ),
    ]
