# Generated by Django 5.0.4 on 2024-09-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_approver_creator_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approver',
            name='creator_name',
        ),
    ]
