# Generated by Django 4.2.5 on 2024-09-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_uploadedimage'),
        ('applications', '0026_remove_approver_creator_name'),
    ]

    operations = [
    ]
