# Generated by Django 4.2.5 on 2024-09-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_merge_20240919_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='approver',
        ),
    ]
