# Generated by Django 4.2.5 on 2024-09-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_delete_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='approver',
            fields=[
                ('application_no', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('coordinate_approval', models.CharField(blank=True, max_length=200, null=True)),
                ('hod_approval', models.CharField(blank=True, max_length=200, null=True)),
                ('vp_approval', models.CharField(blank=True, max_length=200, null=True)),
                ('principal_approval', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
